### ISSUE TITLE
Relative Addressing Labels

### ISSUE THREAD

**Issue by zigon15** [hlorenzi/customasm#25]
At the moment label are basically just a definition of the address they are at I believe. Have you considered adding relative addressing labels? Some instructions in the ISA I am working on such as branches use relative addressing so labels don't work atm. Maybe this is already a thing and I have just missed it?

**Comment by moonheart08** [comment]
you can precalculate relative addresses as part of the instruction definition. In my (relatively complex) assembler definitions, I do

    ld.b r#{imm}, R0 -> {
		reladdr = imm - pc - 2
		assert(reladdr <=  0x7f)
		assert(reladdr >= !0x7f)
		((arith_count * 4) + 9)[7:0] @ !reladdr[7:0]
	}

where `2` is the length of the instruction, and the asserts make sure the relative address is in range.

Ignore the rest tho, it's part of a very silly hack where the immediate load is actually a immediate NOT, and the immediate NOT exists solely because it makes the instructionset come out evenly.

**Comment by zigon15** [comment]
> you can precalculate relative addresses as part of the instruction definition. In my (relatively complex) assembler definitions, I do
> 
> ```
> ld.b r#{imm}, R0 -> {
> 	reladdr = imm - pc - 2
> 	assert(reladdr <=  0x7f)
> 	assert(reladdr >= !0x7f)
> 	((arith_count * 4) + 9)[7:0] @ !reladdr[7:0]
> }
> ```
> 
> where `2` is the length of the instruction, and the asserts make sure the relative address is in range.
> 
> Ignore the rest tho, it's part of a very silly hack where the immediate load is actually a immediate NOT, and the immediate NOT exists solely because it makes the instructionset come out evenly. And all the instrs are defined relative to eachother so adding new ones is easy.

That is perfect thank you, I forgot about the pc def ^_^
