### ISSUE TITLE
No way to sanely represent highly-CISC instruction sets

### ISSUE THREAD

**Issue by moonheart08** [hlorenzi/customasm#38]
Some instruction sets, like that of the DEC VAX, or even x86-64, are currently not representable in customasm without a insanely large cpudef. This could be solved in a few ways, the most doable of them being a way to describe a operand mode as a pattern, so, for example, the instructions of the VAX, which have 26 possible operand modes in any particular operand spot, could be represented as so:
```
#opdef op_byte
{
   ${lit} -> 0b11 @ lit[0:5]
   {reg: gpr} -> 0x5 @ {reg}
   ({reg: gpr}) -> 0x6 @ {reg}
   -({reg: gpr}) -> 0x7 @ {reg}
   ({reg: gpr})+ -> 0x8 @ {reg}
   #{imm: i8} -> 0x8F @ {imm}
   @({reg: gpr}+) -> 0x9 @ {reg}
   @#{imm: i8} -> 0x9F @ {imm}
   b^{disp: s8}({reg: gpr}) -> 0xA @ {gpr} @ {disp}
   ...
}
...
   addb2 {a: op_byte}, {o: op_byte} -> {
      0x80 @ a @ o
   }
   addb3 {a: op_byte}, {b: op_byte}, {o: op_byte} -> {
      0x81 @ a @ b @ o
   }
   addw2 {a: op_word}, {b: op_word}
   addw3 {a: op_word}, {b: op_word}, {o: op_word}
   addl2 {a: op_longword}, {b: op_longword}
...
```
Of course, this still wouldn't work (as the VAX has variable width operands, syntax that's probably incompatible with customasm, and floating point support.), but it'd be a step closer.

**Comment by ProxyPlayerHD** [comment]
i was wondering about the same thing.
i'm currently making an 68k CPU file. And just the MOVE instruction alone has a total of 96 different addressing modes... which is a pain to write.

your suggestion is basically a more complex version of the #tokendef function, and it would massively reduce the size of instructions with lots of addresing modes.
though my personal idea was to just use tokendef directly instead of something seperate:

```
#cpudef "abc"
{
	#bits 16
	
	#tokendef reg
	{
		R0 = 0b0000
		R1 = 0b0001
		R2 = 0b0010
		R3 = 0b0011
	}
	#tokendef source
	{
		{src}		= 0b0000 @ src[3:0]
		({src})		= 0b0001 @ src[3:0]
		({src})+	= 0b0010 @ src[3:0]
		-({src})	= 0b0011 @ src[3:0]
		{src:reg}	= 0b0100 @ src[3:0]
	}
	#tokendef destination
	{
		{dest}		= 0b0000 @ dest[3:0]
		({dest})	= 0b0001 @ dest[3:0]
		({dest})+	= 0b0010 @ dest[3:0]
		-({dest})	= 0b0011 @ dest[3:0]
		-({dest})	= 0b0011 @ dest[3:0]
		{dest:reg}	= 0b0100 @ dest[3:0]
	}
	
	LD {D:destination}, {S:source}		-> D[7:0] @ S[7:0]
}
```
of course it makes the whole assembing process a lot more complicated as tokendef is now dealing with variables, values, and nested tokens instead of just plain characters.

for example when the assembler sees "LD R3, (2)" it has to fiquire out what token to use and how the values fit into it.
in this case it would assemble into -> 0b0100 @ 0b0011 @ 0b0001 @ 2[3:0]

**Comment by hlorenzi** [comment]
I do think this is a fantastic idea! I'll be thinking on how I should go about implementing this.

**Comment by hlorenzi** [comment]
I've taken the time and have been slowly writing this up (on the `dev` branch). For syntax, this is what I have so far:

```asm
#subruledef inner
{
     {x}   => 0x11 @ x`8
    &{x}   => 0x22 @ x`8
    ({x}+) => 0x33 @ x`8
}

#ruledef test
{
    ld {x: inner} => 0x55 @ x`16
}
```

which you can use like:

```asm
ld 0xaa ; = 0x5511aa
ld &0xaa ; = 0x5522aa
ld (0xaa+) ; = 0x5533aa
```

It's like I've merged `#cpudef` and `#tokendef`, so that everything is a `#ruledef` now.

Following community feedback, I've also taken the opportunity to improve the syntax in other places, such as `=>` for the pattern separator, and allowing ambiguous tokens after parameters, such as `({x}+)`. I've changed the directive names here to be more orthogonal with some other ideas I'm having, but I'll probably allow `#cpudef` as a synonym for `#ruledef`.

In any case, what do you guys think?

**Comment by moonheart08** [comment]
That looks /perfect/, honestly.

**Comment by ProxyPlayerHD** [comment]
That is pretty amazing dude, thanks!

**Comment by ProxyPlayerHD** [comment]
actually now that i look at it again i have some questions

1. what exactly is the point of that "#ruledef" directive? does every instruction that uses a different #subruledef need to be in it's own #ruledef, or can all instructions that use some kind of #subruledef share the same #ruledef?
or is it just the synonym for #cpudef like you said, in that case since when can you place #tokendef, #subruledef, etc outside of #cpudef? that's news to me...

2. i hope the documentation gets an update after this, adding features so quickly is really awesome but i think keeping it documented is also really important.

3. do you need to specify the size of "x" in your example? so, do all #subruledef's need to be the same size, or can the bit slice be omitted?

overall, which part of this would not work:

```
#cpudef "test"
{
	#bits 8
	
	#subruledef inner
	{
		{y}	=> 0x11 @ y`8
		&{y}	=> 0x22 @ y`8
		({y}).W	=> 0x44 @ y`16
		({y}).L	=> 0x44 @ y`32
	}
	
	#ruledef test
	{
		LD {x:inner} => 0x55 @ x
		ST {x:inner} => 0x66 @ x
	}
	
	ADD {x:inner} => 0x77 @ x
}
```

**Comment by hlorenzi** [comment]
Nice! It's good that this has allowed us to discuss the new features! In my implementation so far, your code would be written like this:

```asm
#bits 8

#subruledef inner
{
	 {y}    => 0x11 @ y`8
	&{y}    => 0x22 @ y`8
	({y}).W	=> 0x44 @ y`16
	({y}).L	=> 0x44 @ y`32
}

#ruledef test
{
	LD  {x:inner} => 0x55 @ x
	ST  {x:inner} => 0x66 @ x
	ADD {x:inner} => 0x77 @ x
}
```

1. `#ruledef` is a synonym for `#cpudef` -- it's a top-level declaration. But you can now have as many of them as you want, allowing you to split up your definitions. And this also lends itself nicely to replacing `#tokendef`, because you can nest them (by as many levels as necessary). `#subruledef` is exactly the same as `#ruledef`, but it indicates that you can't invoke those rules in your assembly code directly -- they only work as nested parameters. Also, I'm trying to bring `#bits` outside of the rule definitions, so that these new features can work more easily, and to maybe tackle one of the other open issues.

2. Documentation is indeed key, and I should spend more time updating it.

3. Up to this point, you had to specify the size of a nested rule parameter. But I've also realized it would be useful to let the actual size come from the inner rule, so I've been thinking about ways to make that work.

**Comment by ProxyPlayerHD** [comment]
so i could do stuff like this?

```
#bits 8

#subruledef inner
{
	 {y}    => 0x11 @ y`8
	&{y}    => 0x22 @ y`8
	({y}).W	=> 0x44 @ y`16
	({y}).L	=> 0x44 @ y`32
}

#ruledef Load
{
	LD A, {x:inner}		=>	0x50 @ x
	LD B, {x:inner}		=>	0x51 @ x
	LD C, {x:inner}		=>	0x52 @ x
}

#ruledef Store
{
	LD {x:inner}, A		=>	0x60 @ x
	LD {x:inner}, B		=>	0x61 @ x
	LD {x:inner}, C		=>	0x62 @ x
}

#ruledef Add
{
	ADD A, {x:inner}		=> 0x70 @ x
	ADD B, {x:inner}		=> 0x71 @ x
	ADD C, {x:inner}		=> 0x72 @ x
}
```
or alternatively just have everything inside a single `#ruledef` like it works with `#cpudef `right now.

this just an example, in reality i would use `#tokendef` for registers

**Comment by p-rivero** [comment]
This looks like a great improvement over the original system!
Just to make sure I understood correctly how it works, would this be a legal definition?
```
#subruledef REG
{
    r0 => 0x0
    ...
}

#subruledef ALU_OP
{
    mov => 0b000
    and => 0b001
    ...
}

#ruledef CPUDEF
{
    ; ALU operation between 2 registers
    {op: ALU_OP}, {Rd: REG}, {Ra: REG}, {Rb: REG} => 0b00000 @ Rd`4 @ Ra`4 @ 0x000 @ Rb`4

    ; ALU operation between a register and an immediate value
    {op: ALU_OP}, {Rd: REG}, {Ra: REG}, {Imm: i16} => 0b00001 @ Rd`4 @ Ra`4 @ Imm

    ; More instructions
    ...
}
```

**Comment by hlorenzi** [comment]
Yes! Both of your examples would be legal definitions!

**Comment by ProxyPlayerHD** [comment]
will this be in a dev release or do we have to wait til a full one?

**Comment by hlorenzi** [comment]
Okay, everyone! I've released v0.11 with these new features! I've written a [migration guide](https://github.com/hlorenzi/customasm/wiki/Migrating-to-v0.11) for the new syntax. I've also found out that you can easily install new releases from crates.io via `cargo install customasm`. I'll be writing updated usage guides in the future.

Please try it out, and tell me what you think!

**Comment by moonheart08** [comment]
This seems pretty much resolved at this point.
```
#subruledef gpr {
	R0 => 0
	R1 => 1
	R2 => 2
	R3 => 3
	R4 => 4
	R5 => 5
	R6 => 6
	R7 => 7
}

#subruledef stdoperand {
	{x: gpr}, {y: gpr} => x`3 @ y`3 @ 0b00
	({x: gpr}), {y: gpr} => x`3 @ y`3 @ 0b01
	{x: gpr}, ({y: gpr}) => x`3 @ y`3 @ 0b10
	{x: gpr}, {y} => {
		assert(y < 7)
		x`3 @ y`3 @ 0b11
	}
	{x: gpr}, {y} => {
		assert(y >= 7)
		x`3 @ 0b111 @ 0b11 @ y`16
	}
}

#ruledef cpu {
    ld {x: stdoperand} => 0x00 @ x
}


dothing:
    ld r1, r2 
	ld r1, 213 ; 32-bit 
	ld r1, 2   ; 16-bit
	ld (r1), r2
```

**Comment by moonheart08** [comment]
It seems possible to even represent VAX's rather complicated operand set decently cleanly (still need duplication for various operand sizes, but that's peanuts compared to the previous ...probably quadratic growth.

**Comment by p-rivero** [comment]
Amazing job! This is exactly what I had been hoping for.

**Comment by ProxyPlayerHD** [comment]
Yay, time to rewrite 90% of my 68k CPU File!
it's for the better though, so it's fine.

though looking at the "Migrating to v0.11" page, i noticed one thing that reminds me of something i wanted to ask...
have you ever thought about adding support (maybe via command line parameters) for other common notations for Hexadecimal and Binary?
for example a lot of CPUs use `$` for Hex, and `%` for Binary (both are prefixes),
and more Intel-ish ones use `h` for Hex and `b` for Binary (both are suffixes)
those would be (in combination with `0x` and `0b`) the most common notations for Hex/Binary.
