### ISSUE TITLE
Feature Request:  Treat strings as byte arrays.

### ISSUE THREAD

**Issue by TChapman500** [hlorenzi/customasm#49]
I would like to be able to do something like this and have it compile properly:
```
ascii_message:
        #d8 "Hello, World!", 0 ; 8-bit ASCII characters
unicode_message:
        #d16 "Hello, World!, 0 ; 16-bit unicode characters
```

**Comment by mindstorm38** [comment]
For unicode, is null termination 2-bytes wide ?

**Comment by TChapman500** [comment]
Well, as I understand it, the `, 0` at the end has whatever number of bits the `#dXX` defines.  So I don't believe you have to worry about that.  So if the user doesn't specify `, 0`, then it's not null-terminated.

**Comment by hlorenzi** [comment]
Beginning with v0.11, strings are actually treated as UTF-8-encoded byte arrays, and you can use it inside any expression. Be sure to check the [migration guide](https://github.com/hlorenzi/customasm/wiki/Migrating-to-v0.11). In your case, you can do it in one of these ways:

```asm
utf8_message1:
    #d "Hello, World!", 0x00
utf8_message2:
    #d "Hello, World!", 0`8
utf8_message3:
    #d "Hello, World!\0"
```
Note that if you use `#d` without a size specifier, every element must have an explicit size (which strings, hex literals, and bit-slices do). Alternatively, you can just use an escape code for the null byte.

Now, this might not be exactly what you need, since you mentioned ASCII and UTF-16. This isn't implemented yet, but I was imagining a syntax like this:

```asm
ascii_message:
    #d ascii("Hello, World!\0")
utf16be_message:
    #d utf16be("Hello, World!\0")
utf16le_message:
    #d utf16le("Hello, World!\0")
```
This would convert the encoding of the underlying byte array. Note that `"Hello, World!"` is both a valid UTF-8 and a valid ASCII string, so there would be no need for conversion there.

**Comment by TChapman500** [comment]
That'll do.  However, endianness needs to be it's own directive that is applied to the entire processor and not just on a per-string basis.

**Comment by mindstorm38** [comment]
I think andianness of UTF-16 strings has nothing to do with the processor endianness.

**Comment by TChapman500** [comment]
Endianness is a processor thing.

**Comment by moonheart08** [comment]
@TChapman500 Yes, but UTF-16 strings aren't processor specific. There is genuinely two UTF16 standards, the BE and LE versions.
